//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public byte CustomerID { get; set; }
        public Nullable<byte> OrderID { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Address { get; set; }
        public string Cust_Email { get; set; }
        public Nullable<int> Cust_Phone { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
