//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Customers = new HashSet<Customer>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public byte OrderID { get; set; }
        public string OrderRef { get; set; }
        public Nullable<byte> CustomerID { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
