//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public byte QuoteId { get; set; }
        public string QuoteRef { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> QuotePrice { get; set; }
        public Nullable<byte> CustomerId { get; set; }
        public Nullable<byte> StoneTypeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Stone_Type Stone_Type { get; set; }
    }
}
