//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SetInStoneEntities1 : DbContext
    {
        public SetInStoneEntities1()
            : base("name=SetInStoneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer_Table> Customer_Table { get; set; }
        public DbSet<Order_Table> Order_Table { get; set; }
        public DbSet<Product_Table> Product_Table { get; set; }
        public DbSet<Slab_Table> Slab_Table { get; set; }
        public DbSet<Stone_Type> Stone_Type { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
