//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slab
    {
        public Slab()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int SlabId { get; set; }
        public Nullable<int> StoneId { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> CostPerSqMtr { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual Stone Stone { get; set; }
    }
}
