//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stone_Type
    {
        public byte StoneTypeID { get; set; }
        public string StoneType { get; set; }
        public Nullable<decimal> CostPerSqMetre { get; set; }
    
        public virtual Slab_Table Slab_Table { get; set; }
    }
}
